/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 mario.glb -t -T 
Files: mario.glb [19.35KB] > /Users/fant/work/personal-blog/public/models/mario-transformed.glb [6.2KB] (68%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_3002: THREE.Mesh
    Object_3002_1: THREE.Mesh
  }
  materials: {
    mat_head: THREE.MeshStandardMaterial
    mat_eye: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/mario-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-18.508, 4.913, -36.646]} rotation={[-Math.PI, Math.PI / 2, 0]} scale={1.367}>
        <mesh geometry={nodes.Object_3002.geometry} material={materials.mat_head} />
        <mesh geometry={nodes.Object_3002_1.geometry} material={materials.mat_eye} />
      </group>
    </group>
  )
}

useGLTF.preload('/mario-transformed.glb')
