/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 zombie.glb -t -T 
Files: zombie.glb [11.58KB] > /Users/fant/work/personal-blog/public/models/zombie-transformed.glb [8.06KB] (30%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_5003: THREE.Mesh
    Object_5003_1: THREE.Mesh
    Object_5003_2: THREE.Mesh
  }
  materials: {
    ['material_0.001']: THREE.MeshStandardMaterial
    material_1: THREE.MeshStandardMaterial
    material_2: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/zombie-transformed.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[18.193, 8.43, -0.343]} rotation={[Math.PI, 0, Math.PI]} scale={6.3}>
        <mesh geometry={nodes.Object_5003.geometry} material={materials['material_0.001']} />
        <mesh geometry={nodes.Object_5003_1.geometry} material={materials.material_1} />
        <mesh geometry={nodes.Object_5003_2.geometry} material={materials.material_2} />
      </group>
    </group>
  )
}

useGLTF.preload('/zombie-transformed.glb')
