name = "personal-blog"
compatibility_date = "2024-01-01"

[env.production]
routes = [
  { pattern = "*", zone_name = "niccolofanton.dev" }
]

# Disable functions for static site
[functions]
# No functions directory specified - this ensures no functions are deployed 