/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 book.glb -t -T 
Files: book.glb [16.9KB] > /Users/fant/work/personal-blog/public/models/book-transformed.glb [3.97KB] (77%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_2004: THREE.Mesh
    Object_2004_1: THREE.Mesh
    Object_2004_2: THREE.Mesh
  }
  materials: {
    material: THREE.MeshStandardMaterial
    Blanc: THREE.MeshStandardMaterial
    copertina: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const BookModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/book-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <group  >
        <mesh geometry={nodes.Object_2004.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_2004_1.geometry} material={materials.Blanc} />
        <mesh geometry={nodes.Object_2004_2.geometry} material={materials.copertina} />
      </group>
    </group>
  )
})

useGLTF.preload('/models-transformed/book-transformed.glb')
