/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 disc.glb -t -T 
Files: disc.glb [1.16MB] > /Users/fant/work/personal-blog/public/models/disc-transformed.glb [105.61KB] (91%)
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    album: THREE.Mesh
    vinile: THREE.Mesh
  }
  materials: {
    Album_tx: THREE.MeshStandardMaterial
    Vinyl1: THREE.MeshStandardMaterial
  }
  animations: any[]
}

export const DiscModel = React.forwardRef<THREE.Group, JSX.IntrinsicElements['group']>((props, ref) => {
  const { nodes, materials } = useGLTF('/models-transformed/disc-transformed.glb') as GLTFResult
  return (
    <group ref={ref} {...props} dispose={null}>
      <mesh geometry={nodes.album.geometry} material={materials.Album_tx}   />
      <mesh geometry={nodes.vinile.geometry} material={materials.Vinyl1}   />
    </group>
  )
})

useGLTF.preload('/models-transformed/disc-transformed.glb')
